# Generated by Django 4.2.5 on 2023-09-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=1234, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
